import Image from "next/image";
import Header from "./comps/Header";

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div>
      <Header />


      <div className="px-[10%] mt-[50px] flex items-start gap-5 justify-start">

        <div className="flex flex-col gap-5 w-full">
          <div className="font-bold text-[3.8rem] leading-[99%]">
            "
            Masarap sa unang tingin, pag-kinain gusto mo ng ulit-ulitin.
            "
          </div>
          <p className="text-[#888]">
            For individuals aspiring to venture into the food industry
            or enhance their culinary expertise, Developing Delectable Cuisine serves as a crucial asset.
          </p>

          <div className="relative">
            <input
              className="w-[300px] py-[10px] px-[20px] rounded-[30px] border border-[#888] outline-none w-full"
              type="text"
              placeholder="Find more of our specialty"
            />
            <div className="bg-yellow-500 px-[20px] py-[5px] rounded-[30px] font-bold absolute top-[5px] right-[10px] hover: cursor-pointer">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-search-icon lucide-search"><circle cx="11" cy="11" r="8" /><path d="m21 21-4.3-4.3" /></svg>
            </div>
          </div>
        </div>



        <div className="w-full bg-red-500 h-[450px] rounded-[3rem]">
         
        </div>
      </div>



    </div>
  )
}


